tunnel: mytunnel
credentials-file: /home/fareed-sayed/.cloudflared/540cd6ba-a564-48fe-8c3f-9c578bd326bc.json

ingress:
  - hostname: ape.crodlin.in
    service: http://localhost:3000
  - hostname: api-ape.crodlin.in
    service: http://localhost:8000
  - hostname: model-ape.crodlin.in
    service: http://localhost:8001
  - service: http_status:404
