# Generated by Django 4.2.6 on 2025-09-03 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_remove_certificate_additionol_testseries_attempted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='competition_battled',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='competition_won',
        ),
        migrations.AddField(
            model_name='certificate',
            name='date_of_certificate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
