services:
  model:
    build:
      context: ./models
      dockerfile: Dockerfile
    container_name: ape_model_api
    volumes:
      - ./models:/app
    ports:
      - "8001:8001"
    networks:
      - templet

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ape_server_api
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    networks:
      - templet
    depends_on:
      - model

  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   container_name: ape_client_api
  #   volumes:
  #    - ./client:/app
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - templet
  #   depends_on:
  #     - server

  chat_bots:
    build:
      context: ./Chat_bots
      dockerfile: Dockerfile
    container_name: chat_bots_ape_api
    volumes:
    - ./Chat_bots:/app
    ports:
    - "8080:8080"
    networks :
    - templet
    depends_on :
    - server

networks:
  templet:
    driver: bridge
