# Generated by Django 5.1.4 on 2025-09-02 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(choices=[('Tech', 'Tech'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Other', 'Other')], default='Other', max_length=100)),
                ('founded_at', models.DateField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'company_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('stipend', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('skills_required', models.TextField(blank=True, null=True)),
                ('openings', models.IntegerField(default=1)),
                ('application_deadline', models.DateField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'company_internship',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_company', models.BooleanField(default=False)),
                ('is_mentor', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'api_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AiInterviewSampleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_company_data', models.TextField(blank=True, null=True)),
                ('sample_internship_data', models.TextField(blank=True, null=True)),
                ('analysis', models.TextField(blank=True, null=True)),
                ('performance', models.IntegerField(blank=True, null=True)),
                ('communication_skill', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demo_interviews', to='ai_interview.user')),
            ],
        ),
        migrations.CreateModel(
            name='AiDemoInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('sample_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_questions', to='ai_interview.aiinterviewsampledata')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.TextField(blank=True, null=True)),
                ('performance', models.IntegerField(blank=True, null=True)),
                ('communication_skill', models.IntegerField(blank=True, null=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='ai_interview.internship')),
                ('interviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='ai_interview.user')),
            ],
        ),
        migrations.CreateModel(
            name='AiInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_interviews', to='ai_interview.interview')),
            ],
        ),
    ]
