# Generated by Django 5.1.4 on 2025-09-02 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interview', '0002_company_internship_user_aiinterviewsampledata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinterview',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviewer', to='ai_interview.user'),
        ),
        migrations.AlterModelTable(
            name='internship',
            table='company_internship',
        ),
    ]
