services:

  models:
    build:
      context: ../models
      dockerfile: Dockerfile
    container_name: ape_models_api
    volumes:
      - ../models:/app
    ports:
      - "8001:8001"
    networks:
      - templet


networks:
  templet:
    driver: bridge
