# Generated by Django 5.1.4 on 2025-03-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychological_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_bot',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat_bot',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
