# Generated by Django 5.1.4 on 2025-03-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychological_bot', '0002_alter_chat_bot_answer_alter_chat_bot_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychology_user',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
